Files already downloaded and verified
Traceback (most recent call last):

  File "./tests/test-cifar10-mobilenet-customtype-countedfloat32.py", line 25, in <module>
    dll = load_counted_float32()

  File "/root/tests/util/load_datatypes.py", line 298, in load_counted_float32
    RTLD_GLOBAL)

  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: /root/tests/util/../../datatypes/counted-float32/counted-float32.so: cannot open shared object file: No such file or directory

